activation: gelu
alias: null
attn_dropout: 0.0
batch_normalization: false
batch_size: 32
dataloader_kwargs: null
drop_last_loader: false
dropout: 0.2
early_stop_patience_steps: 5
encoder_layers: 3
exclude_insample_y: false
fc_dropout: 0.2
futr_exog_list: null
h: 3
h_train: 1
head_dropout: 0.0
hidden_size: 64
hist_exog_list: null
inference_input_size: 365
inference_windows_batch_size: 1024
input_size: 365
learn_pos_embed: true
learning_rate: 0.0005
linear_hidden_size: 256
loss: !!python/object:neuralforecast.losses.pytorch.DistributionLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _base_distribution: !!python/name:torch.distributions.studentT.StudentT ''
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - quantiles
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDQAAADIzMzc3MTkzMDQ3MDRxAlgDAAAAY3B1cQNLBU50cQRRLoACXXEAWA0AAAAyMzM3
              NzE5MzA0NzA0cQFhLgUAAAAAAAAAAAAAP83MTD3NzMw9ZmZmPzMzcz8=
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  distribution: StudentT
  distribution_kwargs: {}
  domain_map: !!python/name:utils.forecast._noop_student_domain_map ''
  is_distribution_output: true
  num_samples: 1000
  output_names:
  - ''
  - -median
  - !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAAwAAAA
  - !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADgAAAAwAAAA
  - !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADgAAAAwAAAA
  - !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAAwAAAA
  outputsize_multiplier: 3
  param_names:
  - -df
  - -loc
  - -scale
  return_params: false
  scale_decouple: !!python/name:utils.forecast._safe_student_scale_decouple ''
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 500
n_heads: 4
n_samples: 100
n_series: 1
num_lr_decays: -1
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
patch_len: 30
random_seed: 1
res_attention: true
revin: true
revin_affine: false
revin_subtract_last: true
scaler_type: robust
start_padding_enabled: false
stat_exog_list: null
step_size: 1
stride: 15
val_check_steps: 50
valid_batch_size: null
valid_loss: null
windows_batch_size: 1024
